name: Deploy Symfony Static to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build Symfony cache and assets
        run: |
          php bin/console cache:clear --env=prod
          php bin/console asset-map:compile || true

      - name: Start Symfony server
        run: symfony server:start --no-tls --daemon --env=prod

      - name: Wait for server to start
        run: sleep 5

      - name: Generate static HTML snapshot
        run: |
          wget --mirror --convert-links --adjust-extension --page-requisites --no-parent http://127.0.0.1:8000
          mv 127.0.0.1:8000 build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
